# Generated by Django 3.0.7 on 2020-06-20 20:01

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students','Student')
    Student(name="Will Malisch", email="malisch.will@gmail.com", document="250846447",phone="4161234567").save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
